# Generated by Django 5.1.3 on 2024-11-20 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='katagoriler',
            name='seo_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='katagoriler',
            name='seo_title',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='katagoriler',
            name='slug',
            field=models.SlugField(blank=True, max_length=155, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='katagoriler',
            name='ustkategori',
            field=models.ForeignKey(blank=True, help_text='ustkategoriniz varsa girin', null=True, on_delete=django.db.models.deletion.CASCADE, to='urunler.katagoriler'),
        ),
    ]
