# Generated by Django 5.1.3 on 2024-11-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0002_katagoriler_seo_description_katagoriler_seo_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Markalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=155)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('aktifmi', models.BooleanField(default=True)),
                ('seo_title', models.CharField(blank=True, max_length=155, null=True)),
                ('seo_description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=155, null=True, unique=True)),
                ('resim', models.ImageField(blank=True, null=True, upload_to='markaresimleri')),
            ],
            options={
                'verbose_name': 'marka',
                'verbose_name_plural': 'markalar',
            },
        ),
        migrations.AlterModelOptions(
            name='katagoriler',
            options={'verbose_name': 'kategori', 'verbose_name_plural': 'lategoriler'},
        ),
    ]
