# Generated by Django 5.1.3 on 2024-11-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0004_urunler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiketler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=155)),
                ('slug', models.SlugField(blank=True, max_length=155, null=True, unique=True)),
                ('aktifmi', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Etiket',
                'verbose_name_plural': 'Etiketler',
            },
        ),
        migrations.AddField(
            model_name='urunler',
            name='etiketler',
            field=models.ManyToManyField(blank=True, to='urunler.etiketler'),
        ),
    ]
