# Generated by Django 5.1.3 on 2024-11-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0005_etiketler_urunler_etiketler'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='anasayfa',
            field=models.BooleanField(default=False),
        ),
    ]
