# Generated by Django 5.1.3 on 2024-11-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0008_varyasyonlar_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='katagoriler',
            name='aciklama',
            field=models.TextField(blank=True, null=True),
        ),
    ]
