# Generated by Django 5.1.3 on 2024-11-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0010_alter_katagoriler_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='katagoriler',
            name='menudegoster',
            field=models.BooleanField(default=True),
        ),
    ]
